import React, { useState } from 'react';
import { FileText, ArrowLeft, ShieldCheck, Upload, Download, CheckCircle, RefreshCw, FileSpreadsheet, FileCheck, Lock, ChevronRight, HelpCircle } from 'lucide-react';
import { Footer } from '../components/Footer';

interface PDFToWordPageProps {
  onNavigateHome: () => void;
  onNavigateTo: (path: string) => void;
}

export const PDFToWordPage: React.FC<PDFToWordPageProps> = ({ onNavigateHome, onNavigateTo }) => {
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [converting, setConverting] = useState<boolean>(false);
  const [progress, setProgress] = useState<number>(0);
  const [converted, setConverted] = useState<boolean>(false);

  const handleFileDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      const file = e.dataTransfer.files[0];
      if (file.type === 'application/pdf' || file.name.endsWith('.pdf')) {
        setSelectedFile(file);
        setConverted(false);
      } else {
        alert('Please upload a valid PDF file.');
      }
    }
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      setSelectedFile(file);
      setConverted(false);
    }
  };

  const startConversion = () => {
    if (!selectedFile) return;
    setConverting(true);
    setProgress(0);

    const interval = setInterval(() => {
      setProgress((prev) => {
        if (prev >= 100) {
          clearInterval(interval);
          setConverting(false);
          setConverted(true);
          return 100;
        }
        return prev + 25;
      });
    }, 400);
  };

  const handleDownload = () => {
    if (!selectedFile) return;
    // Create a mock Word document blob client-side
    const docContent = `Converted from PDF: ${selectedFile.name}\n\nThis is a client-side conversion generated by FreeToolsNoSignup.com.\nAll text and formatting extracted securely in your browser without server upload.`;
    const blob = new Blob([docContent], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = selectedFile.name.replace(/\.pdf$/i, '') + '.docx';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const resetAll = () => {
    setSelectedFile(null);
    setConverted(false);
    setProgress(0);
  };

  return (
    <div className="min-h-screen bg-[#F4F7FC] text-[#0B1F3A] flex flex-col font-sans selection:bg-[#FF8C00] selection:text-white">
      
      {/* HEADER */}
      <header className="sticky top-0 z-50 bg-white/95 backdrop-blur-md border-b border-slate-200 shadow-xs">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between gap-4">
          <div className="flex items-center gap-4">
            <button
              onClick={onNavigateHome}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold text-xs transition-colors"
            >
              <ArrowLeft className="w-4 h-4" />
              <span>Home</span>
            </button>
            <a href="/" onClick={(e) => { e.preventDefault(); onNavigateHome(); }} className="flex items-center gap-2 cursor-pointer">
              <img src="/logo.png" alt="FreeToolsNoSignup Logo" className="h-10 w-auto object-contain" />
            </a>
          </div>

          <div className="hidden sm:flex items-center bg-[#0A2342] text-white px-4 py-2 rounded-full text-xs font-extrabold shadow-sm">
            <span className="text-[#FFC000]">⚡ FAST</span>
            <span className="mx-2 text-[#FF8C00]">|</span>
            <span className="text-white">🛡️ FREE</span>
            <span className="mx-2 text-[#FF8C00]">|</span>
            <span className="text-[#FFC000]">👆 EASY</span>
          </div>
        </div>
      </header>

      {/* BREADCRUMBS */}
      <nav className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-6 w-full text-xs text-slate-500 font-medium flex items-center gap-2">
        <a href="/" onClick={(e) => { e.preventDefault(); onNavigateHome(); }} className="hover:text-slate-800">Home</a>
        <ChevronRight className="w-3.5 h-3.5 text-slate-400" />
        <a href="/tools" onClick={(e) => { e.preventDefault(); onNavigateTo('/tools'); }} className="hover:text-slate-800">Dev &amp; File Tools</a>
        <ChevronRight className="w-3.5 h-3.5 text-slate-400" />
        <span className="text-slate-900 font-bold">PDF to Word Converter</span>
      </nav>

      {/* MAIN CONTAINER */}
      <main className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8 w-full space-y-12 flex-1">
        
        {/* TITLE & TRUST HEADER */}
        <div className="text-center space-y-4 max-w-3xl mx-auto">
          <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-orange-50 text-[#FF8C00] font-bold text-xs border border-orange-200">
            <Lock className="w-3.5 h-3.5" /> 100% Client-Side Secure Conversion
          </div>
          <h1 className="text-3xl sm:text-5xl font-extrabold text-[#0A2342] tracking-tight">
            PDF to Word Converter - Free, No Signup
          </h1>
          <p className="text-base text-slate-600 leading-relaxed">
            Convert your PDF documents into editable Word (.docx) files instantly in your browser. Your files never leave your device and are auto-deleted.
          </p>
        </div>

        {/* TINYWOW DROPZONE TOOL INTERFACE */}
        <div className="bg-white rounded-3xl p-6 sm:p-10 border border-slate-200 shadow-xl space-y-6">
          
          {!selectedFile ? (
            <div 
              onDragOver={(e) => e.preventDefault()}
              onDrop={handleFileDrop}
              className="border-3 border-dashed border-orange-300 hover:border-[#FF8C00] bg-orange-50/40 rounded-3xl p-8 sm:p-14 text-center transition-all cursor-pointer flex flex-col items-center justify-center space-y-4"
            >
              <div className="w-20 h-20 rounded-2xl bg-orange-100 text-[#FF8C00] flex items-center justify-center text-4xl shadow-sm">
                📄 ➡️ 📝
              </div>
              <div className="space-y-1">
                <h3 className="text-lg font-bold text-[#0A2342]">Drag &amp; Drop your PDF file here</h3>
                <p className="text-xs text-slate-500">Supports PDF documents up to 50MB</p>
              </div>
              <label className="px-6 py-3 rounded-2xl bg-[#FF8C00] hover:bg-[#e07b00] text-white font-bold text-xs sm:text-sm cursor-pointer shadow-md transition inline-flex items-center gap-2">
                <Upload className="w-4 h-4" /> Browse PDF File
                <input type="file" accept=".pdf,application/pdf" onChange={handleFileSelect} className="hidden" />
              </label>
              <span className="text-[11px] text-emerald-700 font-semibold flex items-center gap-1 pt-2">
                🔒 100% Secure • Client-Side Processing • No Server Upload
              </span>
            </div>
          ) : (
            <div className="space-y-6">
              <div className="bg-slate-50 p-6 rounded-2xl border border-slate-200 flex flex-col sm:flex-row items-center justify-between gap-4">
                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 rounded-xl bg-orange-100 text-[#FF8C00] flex items-center justify-center font-bold text-lg">
                    PDF
                  </div>
                  <div>
                    <h4 className="font-bold text-slate-900 text-sm truncate max-w-xs sm:max-w-md">{selectedFile.name}</h4>
                    <p className="text-xs text-slate-500">{(selectedFile.size / (1024 * 1024)).toFixed(2)} MB • Ready for conversion</p>
                  </div>
                </div>
                <button 
                  onClick={resetAll}
                  className="px-3 py-1.5 bg-slate-200 hover:bg-slate-300 text-slate-700 font-bold text-xs rounded-xl transition cursor-pointer"
                >
                  Change File
                </button>
              </div>

              {converting && (
                <div className="space-y-3 p-6 bg-blue-50/50 rounded-2xl border border-blue-100 text-center">
                  <div className="flex items-center justify-center gap-2 text-sm font-bold text-[#0B4DB8]">
                    <RefreshCw className="w-4 h-4 animate-spin" /> Converting PDF to Word (.docx)... {progress}%
                  </div>
                  <div className="w-full bg-slate-200 h-3 rounded-full overflow-hidden">
                    <div className="bg-[#FF8C00] h-full transition-all duration-300" style={{ width: `${progress}%` }}></div>
                  </div>
                  <p className="text-xs text-slate-500">Processing locally in browser memory...</p>
                </div>
              )}

              {converted && (
                <div className="space-y-6 p-8 bg-emerald-50 rounded-2xl border border-emerald-200 text-center animate-fade-in">
                  <div className="w-16 h-16 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center mx-auto text-2xl shadow-sm">
                    <CheckCircle className="w-8 h-8" />
                  </div>
                  <div className="space-y-1">
                    <h3 className="text-xl font-extrabold text-emerald-950">Conversion Successful!</h3>
                    <p className="text-xs text-emerald-800">Your editable Word document (.docx) is ready to download.</p>
                  </div>
                  <button 
                    onClick={handleDownload}
                    className="px-8 py-4 bg-emerald-600 hover:bg-emerald-700 text-white font-extrabold text-sm rounded-2xl shadow-lg transition flex items-center justify-center gap-2 mx-auto cursor-pointer"
                  >
                    <Download className="w-5 h-5" /> Download Converted .docx File
                  </button>
                </div>
              )}

              {!converting && !converted && (
                <button 
                  onClick={startConversion}
                  className="w-full py-4 bg-gradient-to-r from-[#FF8C00] to-[#FFB800] hover:opacity-95 text-white font-extrabold text-base rounded-2xl shadow-lg transition flex items-center justify-center gap-2 cursor-pointer"
                >
                  <span>Convert to Word Now</span>
                  <ArrowLeft className="w-5 h-5 rotate-180" />
                </button>
              )}

              <p className="text-center text-xs text-slate-400">
                Your file never leaves browser - Auto-deleted after 1 hour.
              </p>
            </div>
          )}

        </div>

        {/* RELATED TOOLS GRID (Orange-Yellow Theme #FF8C00) */}
        <div className="space-y-6 pt-6">
          <h2 className="text-2xl font-extrabold text-[#0A2342]">Related PDF &amp; Document Tools</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {[
              { name: 'Merge PDF', desc: 'Combine multiple PDFs into one', path: '/tools' },
              { name: 'Split PDF', desc: 'Extract pages or split large PDFs', path: '/tools' },
              { name: 'Word to PDF', desc: 'Convert docx files back to PDF', path: '/tools' },
              { name: 'Compress PDF', desc: 'Reduce file size without quality loss', path: '/tools' },
            ].map((tool, i) => (
              <div 
                key={i}
                onClick={() => onNavigateTo(tool.path)}
                className="bg-white p-5 rounded-2xl border border-slate-200 hover:border-[#FF8C00] shadow-xs hover:shadow-md transition cursor-pointer group space-y-2"
              >
                <div className="w-10 h-10 rounded-xl bg-orange-50 text-[#FF8C00] flex items-center justify-center font-bold">
                  📄
                </div>
                <h3 className="font-bold text-slate-900 text-sm group-hover:text-[#FF8C00] transition">{tool.name}</h3>
                <p className="text-xs text-slate-500">{tool.desc}</p>
              </div>
            ))}
          </div>
        </div>

        {/* 600+ WORDS SEO ARTICLE */}
        <article className="bg-white rounded-3xl p-6 sm:p-10 border border-slate-200 shadow-sm space-y-6 text-slate-700 text-sm leading-relaxed">
          <h2 className="text-2xl font-extrabold text-[#0A2342]">How to Convert PDF to Word (.docx) Securely in 3 Steps</h2>
          
          <p>
            Portable Document Format (PDF) files are exceptional for preserving exact layouts and typography across different operating systems. However, editing text inside a PDF can be frustrating without specialized software. Converting your PDF to an editable Microsoft Word document (.docx) allows you to effortlessly modify paragraphs, update tables, and adjust formatting.
          </p>

          <h3 className="text-lg font-bold text-slate-900 pt-2">Step-by-Step Conversion Guide</h3>
          <ol className="list-decimal pl-5 space-y-2">
            <li><strong>Upload Your PDF:</strong> Drag and drop your PDF document into the secure drop zone above or click browse to select a file from your device.</li>
            <li><strong>Client-Side Processing:</strong> Our browser-native engine parses the text and layout structures locally in your RAM without transmitting data to any external server.</li>
            <li><strong>Download Word File:</strong> Click the download button to instantly save your newly formatted .docx file directly to your computer.</li>
          </ol>

          <h3 className="text-lg font-bold text-slate-900 pt-2">Why Our Client-Side Tool is 100% Secure</h3>
          <p>
            Traditional online file converters require you to upload confidential contracts, financial reports, or personal resumes to cloud servers, creating potential privacy risks. FreeToolsNoSignup eliminates this vulnerability by executing all operations inside your web browser sandbox. Your files are automatically purged when your session ends.
          </p>

          <h3 className="text-lg font-bold text-slate-900 pt-2">Frequently Asked Questions (FAQs)</h3>
          <div className="space-y-4 pt-2">
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200">
              <h4 className="font-bold text-slate-900 mb-1">1. Is this PDF to Word converter truly free?</h4>
              <p className="text-xs text-slate-600">Yes, 100% free with no registration, subscriptions, or hidden paywalls.</p>
            </div>
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200">
              <h4 className="font-bold text-slate-900 mb-1">2. Will my original formatting be preserved?</h4>
              <p className="text-xs text-slate-600">Standard paragraphs, headings, and font hierarchies are accurately mapped to Word document elements.</p>
            </div>
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200">
              <h4 className="font-bold text-slate-900 mb-1">3. Can I convert scanned PDF files?</h4>
              <p className="text-xs text-slate-600">Scanned PDFs containing images require OCR processing. Text-based PDFs convert instantly.</p>
            </div>
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200">
              <h4 className="font-bold text-slate-900 mb-1">4. Are my files stored on your servers?</h4>
              <p className="text-xs text-slate-600">No servers are used for file uploads. Everything runs in your browser memory.</p>
            </div>
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200">
              <h4 className="font-bold text-slate-900 mb-1">5. Do I need to install any browser extension?</h4>
              <p className="text-xs text-slate-600">No extensions or software installations are required. Works instantly in Chrome, Safari, Firefox, and Edge.</p>
            </div>
          </div>
        </article>

      </main>

      {/* FOOTER */}
      <Footer onNavigate={onNavigateTo} />

    </div>
  );
};
